language: java
jdk: openjdk16
dist: trusty
sudo: required

services:
    - mysql

before_install: 
- cd library-backend-service
- sudo chmod -R 755 /var/lib/mysql/
- sudo mysql -e 'CREATE DATABASE IF NOT EXISTS librarydb;'
- echo "USE mysql;\nUPDATE user SET password=PASSWORD('Hybris123') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
- mvn install -DskipTests -Dmaven.javadoc.skip=true -B -V