language: java
jdk: openjdk16
sudo: required

before_install: 
- cd library-backend-service
- sudo chmod -R 755 /var/lib/mysql/
-  mysql -e 'CREATE DATABASE IF NOT EXISTS library-db;' -u root --p Hybris123

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V